{{- $fullName := include "openjdk-demo-service.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    app: {{ include "openjdk-demo-service.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/acme-challenge-type: "http01"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "openjdk-demo-service"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "openjdk-demo-service"
spec:
  tls:
    - hosts:
        - {{ .Values.dnsname }}
      secretName: tls-secret
  rules:
    - host: {{ .Values.dnsname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-service
                port:
                  name: https
