csisecrets:
  vaultname: ""
  tenantId: ""
  clientId: ""

dnsname: openjdk-demo.local

replicaCount: 1

image:
  repository: gordonbmsft/openjdk-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8443
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 128Mi


env:
  - name: SSL_ENABLED
    value: "true"
  - name: SSL_STORE
    value: "/cert/identity.p12"
  - name: KEY_STORE_PASSWD
    value: ""